/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-24 03:08:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class complaints_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1698109907586L));
    _jspx_dependants.put("jar:file:/C:/Users/DELL/Desktop/FP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cnt/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Complete Responsive Event Organizer Website Design Tutorial</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\" />\n");
      out.write("\n");
      out.write("    <!-- font awesome cdn link  -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\n");
      out.write("\n");
      out.write("    <!-- custom css file link  -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    \n");
      out.write("\n");
      out.write("<header class=\"header\">\n");
      out.write("\n");
      out.write("    <a href=\"#\" class=\"logo\"><span>e</span>vent<span>G</span>eeks</a>\n");
      out.write("\n");
      out.write("    <nav class=\"navbar\">\n");
      out.write("       <a href=\"#home\">home</a>\n");
      out.write("        <a href=\"#service\">service</a>\n");
      out.write("        <a href=\"#about\">about</a>\n");
      out.write("        <a href=\"#gallery\">gallery</a>\n");
      out.write("        <a href=\"#price\">price</a>\n");
      out.write("        <a href=\"#review\">review</a>\n");
      out.write("        <a href=\"#contact\">contact</a>\n");
      out.write("        <a href=\"UserSignUp.jsp\">SignUp</a>\n");
      out.write("        <a href=\"login.jsp\">logIn</a>\n");
      out.write("        <a href=\"uac\">Account</a>\n");
      out.write("        <a href=\"logout\">logOut</a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div id=\"menu-bars\" class=\"fas fa-bars\"></div>\n");
      out.write("    \n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<!-- header section ends -->\n");
      out.write("\n");
      out.write("<h1 class=\"heading\">client's <span>review</span></h1>\n");
      out.write("<h1 class=\"heading\"> C<span>omplaints</span> </h1>\n");
      out.write("<!--Complaints starts-->\n");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"contact\" id=\"contact\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("    <form action=\"complaint\" method=\"post\">\n");
      out.write("        <div class=\"inputBox\">\n");
      out.write("            <input name= \"name\" type=\"text\" placeholder=\"name\">\n");
      out.write("            <input name =\"email\" type=\"email\" placeholder=\"email\">\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <textarea name=\"complaint\" placeholder=\"your message\" id=\"\" cols=\"30\" rows=\"10\"></textarea>\n");
      out.write("        <input  name=\"submit\" type=\"submit\" value=\"File Complaint\" class=\"btn\">\n");
      out.write("        \n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!--Complaints ends-->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- footer section starts  -->\n");
      out.write("\n");
      out.write("<section class=\"footer\">\n");
      out.write("\n");
      out.write("    <div class=\"box-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"box\">\n");
      out.write("            <h3>contact info</h3>\n");
      out.write("            <a href=\"#\"> <i class=\"fas fa-phone\"></i> +94767921858 </a>\n");
      out.write("            <a href=\"#\"> <i class=\"fas fa-phone\"></i> +94775193445 </a>\n");
      out.write("            <a href=\"#\"> <i class=\"fas fa-envelope\"></i> mudithapradeeptha@gmail.com </a>\n");
      out.write("            <a href=\"#\"> <i class=\"fas fa-envelope\"></i> bhagyadewmi17@gmail.com </a>\n");
      out.write("            <a href=\"#\"> <i class=\"fas fa-map-marker-alt\"></i> colombo, sri lanka - 400104 </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"box\">\n");
      out.write("            <h3>follow us</h3>\n");
      out.write("            <a href=\"#\"> <i class=\"fab fa-facebook-f\"></i> facebook </a>\n");
      out.write("            <a href=\"#\"> <i class=\"fab fa-twitter\"></i> twitter </a>\n");
      out.write("            <a href=\"#\"> <i class=\"fab fa-instagram\"></i> instagram </a>\n");
      out.write("            <a href=\"#\"> <i class=\"fab fa-linkedin\"></i> linkedin </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"credit\"> created by <span>MMBP Designers</span> | all rights reserved </div>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- footer section ends -->\n");
      out.write("\n");
      out.write("<!-- theme toggler  -->\n");
      out.write("\n");
      out.write("<div class=\"theme-toggler\">\n");
      out.write("\n");
      out.write("    <div class=\"toggle-btn\">\n");
      out.write("        <i class=\"fas fa-cog\"></i>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <h3>choose color</h3>\n");
      out.write("\n");
      out.write("    <div class=\"buttons\">\n");
      out.write("        <div class=\"theme-btn\" style=\"background: #3867d6;\"></div>\n");
      out.write("        <div class=\"theme-btn\" style=\"background: #f7b731;\"></div>\n");
      out.write("        <div class=\"theme-btn\" style=\"background: #5c2274;\"></div>\n");
      out.write("        <div class=\"theme-btn\" style=\"background: #20bf6b;\"></div>\n");
      out.write("        <div class=\"theme-btn\" style=\"background: #fa8231;\"></div>\n");
      out.write("        <div class=\"theme-btn\" style=\"background: #FC427B;\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- custom js file link  -->\n");
      out.write("<script src=\"js/script.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
